name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install pipreqs
        run: pip install pipreqs

      - name: Generate requirements.txt
        run: pipreqs . --force

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Install http2
        run: pip install httpx[http2]

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest
